"use client";

import * as React from "react";
import {
  X,
  ShieldCheck,
  Download,
  FileCheck,
} from "lucide-react";
import { ComplianceDocument } from "@/types/compliance";

interface CertificateModalProps {
  document: ComplianceDocument | null;
  isOpen: boolean;
  onClose: () => void;
}

export function CertificateModal({
  document: doc,
  isOpen,
  onClose,
}: CertificateModalProps) {
  if (!isOpen || !doc) return null;

  const handleDownload = () => {
    // Printable / savable certificate sheet in a clean popup
    const certWindow = window.open("", "_blank");
    if (certWindow) {
      certWindow.document.write(`
        <!DOCTYPE html>
        <html>
        <head>
          <title>Compliance Certificate - ${doc.id}</title>
          <style>
            body { font-family: 'Inter', -apple-system, sans-serif; padding: 48px; color: #0f172a; max-width: 640px; margin: 0 auto; }
            .header { border-bottom: 2px solid #1e4c77; padding-bottom: 20px; margin-bottom: 24px; }
            .title { font-size: 18px; font-weight: 600; color: #1e4c77; letter-spacing: -0.02em; }
            .subtitle { font-size: 12px; color: #64748b; margin-top: 4px; }
            .card { background: #f8fafc; border: 1px solid #e2e8f0; border-radius: 12px; padding: 20px; margin: 24px 0; }
            .row { display: flex; justify-content: space-between; padding: 8px 0; font-size: 12.5px; border-bottom: 1px solid #f1f5f9; }
            .row:last-child { border-bottom: none; }
            .label { color: #64748b; }
            .val { font-weight: 500; color: #0f172a; }
            .notice { font-size: 11px; color: #64748b; background: #ebf4fb; border: 1px solid #bfdbfe; border-radius: 8px; padding: 12px; margin-top: 20px; }
          </style>
        </head>
        <body>
          <div class="header">
            <div class="title">Compliance Clearance Certificate</div>
            <div class="subtitle">FINRA Rule 2210 & SEC Rule 206(4)-1 Approved</div>
          </div>
          <div class="card">
            <div class="row"><span class="label">Document Title:</span><span class="val">${doc.title}</span></div>
            <div class="row"><span class="label">Certificate ID:</span><span class="val">CERT-${doc.id.replace("DOC-", "")}-OK</span></div>
            <div class="row"><span class="label">Document ID:</span><span class="val">${doc.id}</span></div>
            <div class="row"><span class="label">Supervisory Officer:</span><span class="val">${doc.officer_name || "Sarah Jenkins (Series 24)"}</span></div>
            <div class="row"><span class="label">Approval Period:</span><span class="val">${doc.reviewed_at ? new Date(doc.reviewed_at).toLocaleDateString() : "March 02, 2026"}</span></div>
            <div class="row"><span class="label">Version Approved:</span><span class="val">v${doc.version} (Final)</span></div>
          </div>
          <div class="notice">This certificate satisfies SEC Rule 17a-4 recordkeeping retention requirements. Generated by Verity Compliance Review.</div>
          <script>window.print();</script>
        </body>
        </html>
      `);
      certWindow.document.close();
    }
    onClose();
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-900/40 backdrop-blur-xs p-4 font-inter select-none animate-in fade-in duration-150">
      <div className="w-full max-w-md rounded-2xl bg-white shadow-xl border border-slate-200/90 overflow-hidden flex flex-col font-inter animate-in zoom-in-95 duration-150">
        {/* Minimal Header */}
        <div className="px-5 py-4 border-b border-slate-100 bg-slate-50/70 flex items-center justify-between font-inter">
          <div className="flex items-center gap-2.5">
            <div className="h-8 w-8 rounded-xl bg-[#ebf4fb] border border-[#2575bc]/20 text-[#1e4c77] flex items-center justify-center shadow-2xs shrink-0">
              <FileCheck className="h-4 w-4 stroke-[1.8]" />
            </div>
            <div>
              <h3 className="text-[13px] font-medium text-slate-800 font-inter">
                Compliance Clearance Certificate
              </h3>
              <p className="text-[11px] text-slate-400 font-normal font-inter">
                FINRA Rule 2210 & SEC Rule 206(4)-1
              </p>
            </div>
          </div>

          <button
            type="button"
            onClick={onClose}
            aria-label="Close modal"
            className="h-7 w-7 rounded-lg text-slate-400 hover:text-slate-700 hover:bg-slate-100 flex items-center justify-center transition-colors cursor-pointer"
          >
            <X className="h-4 w-4 stroke-[1.8]" />
          </button>
        </div>

        {/* Certificate Details */}
        <div className="p-5 space-y-3 font-inter">
          <div className="rounded-xl bg-slate-50/70 border border-slate-200/70 p-3.5 space-y-2 text-xs font-inter">
            <div className="flex justify-between items-baseline gap-2">
              <span className="text-slate-400 font-normal">Document</span>
              <span className="font-medium text-slate-800 text-right truncate max-w-[210px]" title={doc.title}>
                {doc.title}
              </span>
            </div>
            <div className="flex justify-between items-baseline">
              <span className="text-slate-400 font-normal">Certificate Hash</span>
              <span className="font-numbers text-[#1e4c77] font-medium text-[11px]">
                CERT-{doc.id.replace("DOC-", "")}-OK
              </span>
            </div>
            <div className="flex justify-between items-baseline">
              <span className="text-slate-400 font-normal">Supervisory Officer</span>
              <span className="font-medium text-slate-800">
                {doc.officer_name || "Sarah Jenkins (Series 24)"}
              </span>
            </div>
            <div className="flex justify-between items-baseline">
              <span className="text-slate-400 font-normal">Approval Date</span>
              <span className="font-numbers text-slate-700">
                {doc.reviewed_at ? "March 02, 2026" : "Current Period"}
              </span>
            </div>
            <div className="flex justify-between items-baseline">
              <span className="text-slate-400 font-normal">Version</span>
              <span className="font-numbers text-slate-700">v{doc.version} (Final)</span>
            </div>
          </div>

          <div className="flex items-start gap-2 text-[11px] text-slate-600 bg-[#ebf4fb]/50 border border-[#2575bc]/15 p-2.5 rounded-xl font-inter leading-relaxed">
            <ShieldCheck className="h-4 w-4 text-[#1e4c77] shrink-0 mt-0.5 stroke-[1.8]" />
            <span>
              This certificate satisfies SEC Rule 17a-4 recordkeeping retention requirements.
            </span>
          </div>
        </div>

        {/* Minimal Actions Footer */}
        <div className="px-5 py-3.5 border-t border-slate-100 bg-slate-50/50 flex items-center justify-end gap-2 font-inter">
          <button
            type="button"
            onClick={onClose}
            className="h-8.5 px-3.5 rounded-lg border border-slate-200 bg-white hover:bg-slate-50 text-xs font-normal text-slate-700 transition-all cursor-pointer shadow-2xs font-inter"
          >
            Close
          </button>
          <button
            type="button"
            onClick={handleDownload}
            className="h-8.5 px-3.5 rounded-lg bg-[#1e4c77] hover:bg-[#163e63] active:bg-[#112f4c] text-white text-xs font-normal transition-all shadow-xs flex items-center gap-1.5 cursor-pointer font-inter"
          >
            <Download className="h-3.5 w-3.5 stroke-[1.8]" />
            <span>Download Certificate</span>
          </button>
        </div>
      </div>
    </div>
  );
}
