"""initial schema

Revision ID: 1cdbe98ea76f
Revises:
Create Date: 2026-09-03 22:35:07.304765

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy

# revision identifiers, used by Alembic.
revision: str = "1cdbe98ea76f"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    op.create_table(
        "rules",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("type", sa.String(), nullable=False),
        sa.Column("embedding", pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("role", sa.Enum("advisor", "officer", name="userrole"), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("hashed_password", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_table(
        "documents",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("advisor_id", sa.UUID(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("pending_review", "approved", "rejected", "needs_revision", name="documentstatus"),
            nullable=False,
        ),
        sa.Column("file_reference", sa.String(), nullable=False),
        sa.Column("type", sa.Enum("pdf", "docx", "xlsx", name="documenttype"), nullable=False),
        sa.Column("uploaded_at", sa.DateTime(), nullable=True),
        sa.Column("thread_id", sa.UUID(), nullable=False),
        sa.Column("replaces_document_id", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(
            ["advisor_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["replaces_document_id"],
            ["documents.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "ai_analysis",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("document_id", sa.UUID(), nullable=False),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("generated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["documents.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("document_id", name="uq_ai_analysis_document"),
    )
    op.create_table(
        "audit_events",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("actor_id", sa.UUID(), nullable=False),
        sa.Column("document_id", sa.UUID(), nullable=False),
        sa.Column(
            "action",
            sa.Enum("submitted", "viewed", "decided", "resubmitted", name="auditaction"),
            nullable=False,
        ),
        sa.Column("timestamp", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["actor_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["documents.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "pii_mappings",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("document_id", sa.UUID(), nullable=False),
        sa.Column("placeholder", sa.String(), nullable=False),
        sa.Column("original_value", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["documents.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "precedent_index",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("document_id", sa.UUID(), nullable=False),
        sa.Column("masked_text", sa.Text(), nullable=False),
        sa.Column(
            "decision", sa.Enum("approved", "rejected", "needs_revision", name="reviewstatus"), nullable=False
        ),
        sa.Column("comment", sa.Text(), nullable=True),
        sa.Column("embedding", pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=True),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["documents.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "reviews",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("document_id", sa.UUID(), nullable=False),
        sa.Column("officer_id", sa.UUID(), nullable=False),
        sa.Column(
            "status", sa.Enum("approved", "rejected", "needs_revision", name="reviewstatus"), nullable=False
        ),
        sa.Column("comment", sa.Text(), nullable=True),
        sa.Column("decided_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["documents.id"],
        ),
        sa.ForeignKeyConstraint(
            ["officer_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "flags",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("analysis_id", sa.UUID(), nullable=False),
        sa.Column("passage_excerpt", sa.Text(), nullable=False),
        sa.Column("matched_rule_id", sa.UUID(), nullable=True),
        sa.Column("explanation", sa.Text(), nullable=False),
        sa.Column("severity", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["analysis_id"],
            ["ai_analysis.id"],
        ),
        sa.ForeignKeyConstraint(
            ["matched_rule_id"],
            ["rules.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("flags")
    op.drop_table("reviews")
    op.drop_table("precedent_index")
    op.drop_table("pii_mappings")
    op.drop_table("audit_events")
    op.drop_table("ai_analysis")
    op.drop_table("documents")
    op.drop_table("users")
    op.drop_table("rules")
    op.execute("DROP EXTENSION IF EXISTS vector")
    # ### end Alembic commands ###
