"""add ON DELETE SET NULL to flags.matched_rule_id

Revision ID: af48452abec6
Revises: efb7cc15507d
Create Date: 2026-09-09 20:34:17.424848

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af48452abec6'
down_revision: Union[str, None] = 'efb7cc15507d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('flags_matched_rule_id_fkey', 'flags', type_='foreignkey')
    op.create_foreign_key(None, 'flags', 'rules', ['matched_rule_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'flags', type_='foreignkey')
    op.create_foreign_key('flags_matched_rule_id_fkey', 'flags', 'rules', ['matched_rule_id'], ['id'])
    # ### end Alembic commands ###
