"""add original_filename to documents

Revision ID: d74f6a286d02
Revises: 5bbc28459ce6
Create Date: 2026-09-10 20:08:54.340389

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd74f6a286d02'
down_revision: Union[str, None] = '5bbc28459ce6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('original_filename', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'original_filename')
    # ### end Alembic commands ###
