"""
Given a masked text chunk and its candidate rules (from retrieval), asks
the LLM whether the chunk actually violates any of them. The LLM never
decides a review outcome -- it only proposes flags for a human officer to
evaluate, per the brief's "the AI never decides" constraint.

Passages are taken directly from the chunk (not generated by the model),
so a flag's quoted text is always exactly what's in the document -- the
model only supplies the explanation and severity judgment.
"""

import json

from google.genai import types

GENERATION_MODEL = "gemini-3.5-flash-lite"

FLAG_PROMPT_TEMPLATE = """You are a compliance assistant reviewing a passage from a financial advisor's client-facing document. You are NOT making a final decision -- a human compliance officer will review your output.

Passage to check:
\"\"\"{passage}\"\"\"

Candidate rules this passage might violate (found via retrieval, may or may not actually apply):
{rules_block}

For each rule the passage genuinely violates, return an entry. If the passage does not violate any of the given rules, return an empty list.

Respond ONLY with a JSON array, no other text, in this exact format:
[
  {{"rule_id": "<rule id from the list above>", "explanation": "<one sentence: why this passage conflicts with this rule>", "severity": "low" | "medium" | "high"}}
]
"""


def _format_rules_block(rules) -> str:
    return "\n".join(f"- [{r.id}] ({r.type}) {r.text}" for r in rules)


def generate_flags_for_chunk(client, passage: str, candidate_rules) -> list[dict]:
    """
    Returns a list of dicts: {rule_id: str, explanation: str, severity: str}.
    Does NOT include 'passage' -- caller already has it (it's the chunk
    itself), so the model is never trusted to reproduce quoted text.
    Returns [] on any parse failure rather than raising, since a single
    chunk's flagging failure shouldn't take down the whole document's
    analysis -- see analyze_document.py for how failures are handled there.
    """
    if not candidate_rules:
        return []

    prompt = FLAG_PROMPT_TEMPLATE.format(
        passage=passage,
        rules_block=_format_rules_block(candidate_rules),
    )

    import time
    for attempt in range(3):
        try:
            response = client.models.generate_content(
                model=GENERATION_MODEL,
                contents=prompt,
                config=types.GenerateContentConfig(
                    response_mime_type="application/json",
                    temperature=0.1,
                ),
            )
            break
        except Exception:
            if attempt == 2:
                raise
            time.sleep(2 ** attempt)

    try:
        raw_flags = json.loads(response.text)
    except (json.JSONDecodeError, TypeError):
        return []

    valid_rule_ids = {str(r.id) for r in candidate_rules}
    flags = []
    for f in raw_flags:
        if not isinstance(f, dict):
            continue
        rule_id = f.get("rule_id")
        if rule_id not in valid_rule_ids:
            continue  # model hallucinated a rule id not in the candidates -- drop it
        severity = f.get("severity") if f.get("severity") in ("low", "medium", "high") else "medium"
        flags.append({
            "rule_id": rule_id,
            "explanation": f.get("explanation", "").strip() or "No explanation provided.",
            "severity": severity,
        })
    return flags
